sudo: false
matrix:
  include:
    - language: "java"
      jdk: "openjdk8"
      env:
        - OPENCGA_HOME=$TRAVIS_BUILD_DIR/opencga/opencga-app/build
        - MONGODB_VERSION=4.0.18
      install:
        - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
        - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
        - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
        - mkdir -p data/db
        - mongod --dbpath=data/db &
        - mongod --version
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -PTravis
      script:
        - mvn test -s .travis.settings.xml -PTravis
